services:
    tfox.di_tools.kernel_request_listener:
        class: TFox\DiToolsBundle\Listener\KernelControllerListener
        arguments: [ "@service_container" ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }